# -*- coding: utf-8 -*-
"""clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lO8GwySYd03tuDySzpGemu_jqcmoDexW

$$ Clustering $$

---
# `#` Import Necessary Libraries
"""

from sklearn.cluster import KMeans
import umap

"""---
# `#` Dimension Reduction
"""

def reduce_dimensions(features, n_components=2):
    """Reduces feature dimensions using UMAP."""
    reducer = umap.UMAP(n_components=n_components, random_state=42)
    return reducer.fit_transform(features)

"""---
# `#` KMeans Cluster
"""

def apply_kmeans(features, n_clusters=5):
    """Clusters data using K-Means."""
    model = KMeans(n_clusters=n_clusters, random_state=42)
    return model.fit_predict(features)