# -*- coding: utf-8 -*-
"""feature_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lO8GwySYd03tuDySzpGemu_jqcmoDexW

$$ Feature \space Extraction $$

---
# `#` Import Necessary Libraries
"""

import torch
from transformers import BertTokenizer, BertModel
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
import numpy as np

"""---
# `#` Feature Extraction

## `i` tfidf
"""

def extract_features_tfidf(corpus):
    """Applies TF-IDF vectorization."""
    vectorizer = TfidfVectorizer()
    return vectorizer.fit_transform(corpus)

"""## `ii` Bert"""

def extract_features_bert(corpus):
    """Generates BERT embeddings for given text corpus."""
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertModel.from_pretrained('bert-base-uncased')
    embeddings = []
    for text in corpus:
        inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True, max_length=512)
        with torch.no_grad():
            outputs = model(**inputs)
        embeddings.append(outputs.last_hidden_state[:, 0, :].squeeze().numpy())
    return np.array(embeddings)

"""---
# `#` Scale
"""

def scale_features(features):
    """Applies standard scaling to the features."""
    scaler = StandardScaler()
    return scaler.fit_transform(features)